- hosts: bitbsd
  remote_user: root
  gather_facts: no

  tasks:


  - name: update software on lightning1
    raw: "jexec lightning1 sh -c 'cd /tmp/bitbsd-clouds/ && git pull'"

  - name: make scripts global on lightning1
    shell: "jexec lightning1 sh -c 'ln -sf /tmp/bitbsd-clouds/lightningd/*.sh /usr/local/bin/'"

  - name: stop lightning1
    shell: cbsd jstop lightning1

  - name: create cloned jail
    shell: "cbsd jclone old=lightning1 new={{ cname }} host_hostname='{{ cname }}.bitclouds.sh' ip4_addr=DHCP"

  - name: start lightning1
    shell: cbsd jstart lightning1

  - name: start cloned jail
    shell: "cbsd jstart {{ cname }}"

  - name: enable TOR in jail
    shell: "jexec {{ cname }} sysrc tor_enable=YES"

  - name: start TOR
    shell: "jexec {{ cname }} service tor start"

  - name: Setup alternate SSH port
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/etc/ssh/sshd_config"
      regexp: "^#Port"
      line: "Port {{ sshport }}"

  - name: Add RPC host to bitcoin-cli
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/home/lightning/.bitcoin/bitcoin.conf"
      regexp: "^rpcconnect="
      line: "rpcconnect=192.168.0.2"

  - name: Add RPC user to bitcoin-cli
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/home/lightning/.bitcoin/bitcoin.conf"
      regexp: "^rpcuser="
      line: "rpcuser={{ rpcusr }}"

  - name: Add RPC pass to bitcoin-cli
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/home/lightning/.bitcoin/bitcoin.conf"
      regexp: "^rpcpassword="
      line: "rpcpassword={{ rpcpwd }}"

  - name: Set alias on LN
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/home/lightning/.lightning/config"
      regexp: "^alias="
      line: "alias={{ alias }}"

  - name: Bridge SSH to .onion
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/usr/local/etc/torrc"
      regexp: "^HiddenServicePort 22 localhost:22"
      line: "HiddenServicePort 22 localhost:{{ sshport }}"

  - name: Read onion address in jail
    shell: "jexec {{ cname }} cat /var/db/tor/clightning/hostname"
    register: onion

  - name: Change LN announce-addr
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/home/lightning/.lightning/config"
      regexp: "^announce-addr="
      line: "announce-addr={{ onion.stdout }}:9735"

  - name: set lightning user password
    raw: "jexec {{ cname }} sh -c 'echo \"{{ pwd }}\" | pw usermod lightning -h0'"

  - name: Setup ssh on start
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/etc/rc.conf"
      regexp: "^sshd_enable"
      line: "sshd_enable=YES"

  - name: stop cloned jail
    shell: "cbsd jstop {{ cname }}"

  - name: start cloned jail
    shell: "cbsd jstart {{ cname }}"
