- hosts: bitbsd
  remote_user: root
  gather_facts: no

  tasks:

  - name: update software on rootshell1
    raw: "jexec rootshell1 sh -c 'rm -rf /tmp/bitbsd-clouds && cd /tmp/ && git clone https://github.com/bitcoin-software/bitbsd-clouds'"

  - name: make executables in tools directory
    raw: "jexec rootshell1 sh -c 'chmod +x /tmp/bitbsd-clouds/rootshell/*.sh'"

  - name: make scripts global on rootshell1
    shell: "jexec rootshell1 sh -c 'ln -sf /tmp/bitbsd-clouds/rootshell/*.sh /usr/local/bin/'"

  - name: stop rootshell1
    shell: cbsd jstop rootshell1

  - name: create cloned rootshell jail
    shell: "cbsd jclone old=rootshell1 new={{ cname }} host_hostname='{{ cname }}.bitclouds.sh' ip4_addr=DHCP"

  - name: start rootshell1 jail
    shell: cbsd jstart rootshell1

  - name: start cloned rootshell jail
    shell: "cbsd jstart {{ cname }}"

  - name: Setup alternate SSH port on rootshell jail
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/etc/ssh/sshd_config"
      regexp: "^#Port"
      line: "Port {{ sshport }}"

  - name: get jail ip addr
    shell: jls | grep {{ cname }} | egrep -o '192.168.0.[0-9]+'
    register: jailip

  - name: Set torsocks addr in lightning jail
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/usr/local/etc/tor/torsocks.conf"
      regexp: "^TorAddress"
      line: "TorAddress {{ jailip.stdout }}"


  - name: set satoshi user password on rootshell jail
    raw: "jexec {{ cname }} sh -c 'echo \"{{ pwd }}\" | pw usermod satoshi -h0'"

  - name: Setup ssh on start on rootshell jail
    lineinfile:
      dest: "/zroot/jails/jails/{{ cname }}/etc/rc.conf"
      regexp: "^sshd_enable"
      line: "sshd_enable=YES"

  - name: stop cloned rootshell jail
    shell: "cbsd jstop {{ cname }}"

  - name: start cloned rootshell jail
    shell: "cbsd jstart {{ cname }}"
