- hosts: bitbsd
  remote_user: root
  gather_facts: no

  tasks:
  - name: create {{ iname }}
    shell: >
      cbsd bcreate
      jname={{ iname }}
      vm_os_type=linux
      vm_os_profile=cloud-ubuntuserver-amd64-20.04
      vm_cpus=1
      vm_ram=2g
      imgsize=40g
      runasap=1
      ci_gw4=192.168.3.1 ci_ip4_addr={{ lan_ip }}
      ci_fqdn={{ dname }}.bitclouds.sh
      ci_user_add=user
      ci_user_pw_user={{ pwd }}
      ci_user_pubkey_user='{{ pub_key }}'
      ci_user_pw_root={{ pwd }}